# Generated by Django 2.0 on 2020-09-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
