# Generated by Django 2.0 on 2020-10-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_scroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerImage', models.CharField(max_length=1000)),
                ('aboutUs', models.CharField(max_length=10000)),
            ],
        ),
    ]
